### ISSUE TITLE
Can't delete users

### ISSUE THREAD

**Issue by need4swede** [gtsteffaniak/filebrowser#122]
**Description**
Can't delete users in the UI

**Expected behaviour**
Clicking 'Delete' should delete a user. The original Filebrowser opens a confirmation window and then deletes the user.

**What is happening instead?**
Clicking delete does nothing.

**Additional context**
Running in Docker (Windows); Firefox/Chrome

**How to reproduce?**
1. Create user
2. Try to delete user from User Management page

**Comment by gtsteffaniak** [comment]
thanks for reporting, will create a fix for this in the next release (this week)
