### ISSUE TITLE
Cannot download a folder in single-click mode

### ISSUE THREAD

**Issue by feklee** [gtsteffaniak/filebrowser#214]
**Description**

I am using Filebrowser exclusively on Firefox for Android. (Firefox because it has a built-in PDF viewer)

In double-click mode, I can select a folder by single tapping. Then I long-press, and then I tap *Download*, to download it. In single-click mode I couldn't figure out how to download a folder. I prefer single-click mode.

**Expected behaviour**

What would be intuitive, at least to me: Longpress a folder, and then there is a popup where I can select to download it. (After long-pressing, there could also be a way to select this and other items.)

Or, like in the regular Filebrowser, have a menu that offers download, although that took me a while to discover.

I always found the UI of the Dropbox mobile client quite good. I think it has the aforementioned long-press functionality, but I would need to install it again to check. I moved away from Dropbox to my own server with Syncthing.

**What is happening instead?**

I couldn't find a way to download a folder in single-click mode.

**How to reproduce?**

Try to download a folder in single-click mode. If it's possible, then I'm happy with an explanation on how to do it, and the issue is solved.

**Comment by gtsteffaniak** [comment]
This is a bug - the expected process should be (when using single click mode):

1. enabling selection mode from the right-click context menu
2. making selection to files
3. right-click context menu download action , or other action

 I see that this is not working as expected. 

Will fix in v0.2.10

**Comment by gtsteffaniak** [comment]
fixed in v0.2.10

**Comment by feklee** [comment]
Will compile the new version and try, thank you!

**Comment by feklee** [comment]
It took me a while to figure out how to download a folder (in case others are wondering):

 1. Long tap on the folder, and a context menu shows up.

 2. Tap on: *Select multiple*

 3. Tap on the folder.

 4. Long tap on the folder (again) to show up another context menu.

 5. Tap on: *Download*

 6. Tap on desired archive format, which initiates the download in a new tab, at least in Firefox.

 7. Go back to the previous tab.

 8. Use the back button or gesture to leave *Select multiple*, which also goes up in the hierarchy to the parent folder.

 9. Go back into the folder you were in.

**Comment by gtsteffaniak** [comment]
Yep, multi select mode needs to be enabled first when in Single click mode... Not sure how to get around that. I provided a more succinct 3 steps a couple comments above.
