### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by baedlowi** [gtsteffaniak/filebrowser#239]
**Description**
When creating new user through the web, get error :not found

**Files**
![Screenshot_20241121_155239](https://github.com/user-attachments/assets/588188b6-c315-42e7-9def-63cb82da07d4)

**Comment by gtsteffaniak** [comment]
Thanks for reporting, I'll check what happened and create a hotfix for the current version today

**Comment by gtsteffaniak** [comment]
fixed in v0.3.0 hotfix, pull gtstef/filebrowser again from docker to get the latest version
