### ISSUE TITLE
Windows Reports .exe as Malicious

### ISSUE THREAD

**Issue by generallund** [gtsteffaniak/filebrowser#253]
**Description**
Windows Defender reports latest amd64.exe as Trojan:Win32/Wacatac.B!ml, automatically quarantining the file for "suspected remote command and control execution."

**Additional context**
Default Windows Defender settings on a Windows 11 Pro instance, as well as default Windows Defender settings for a Windows Server 2022 system.

**How to reproduce?**
Defender was triggered on download, before the .exe was accessed or attempted to run.

**Files**
windows-amd64-filebrowser.exe

**Comment by gtsteffaniak** [comment]
Thanks for opening the issue, I think this is a common thing for a lot of go based executables. I'll see if there's anything that can be done.

I generally discourage using the windows executable, as noted at the top of the readme. I don't ever test with it and docker on windows is easy with WSL , so there's better alternatives.

**Comment by generallund** [comment]
Yeah I intend to setup the docker for it, just wanted to let you know :)

**Comment by gtsteffaniak** [comment]
disabling windows build in future releases... no clue why its flagged

**Comment by gtsteffaniak** [comment]
Just an FYI, v0.3.5 and beyond, I will build the windows release on a windows machine (rather than in github actions automatically), which resolves this where I tested it.

I have also tested the windows version a bit and confirmed it generally works as expected (at this time).

**Comment by generallund** [comment]
So I figured out how to setup WSL and Docker on a Windows Server instance for nothing??? Haha but seriously, awesome work! Thanks

**Comment by gtsteffaniak** [comment]
Maybe haha, docker and WSL is good to have available for so many things!
