### ISSUE TITLE
Shorten the download link

### ISSUE THREAD

**Issue by gtsteffaniak** [gtsteffaniak/filebrowser#27]
clone from https://github.com/filebrowser/filebrowser/issues/2619

In adition to https://example.com/api/public/dl/file-id
the user could also use https://example.com/dl/file-id
Or maybe https://example.com/file-id/dl...
That would make the shared link much more clean, short and easy to remember.

It would be especially useful in conjunction with this request: https://github.com/filebrowser/filebrowser/issues/2566

**Comment by trmdi** [comment]
Are you about to implement this feature on your repo only or will make a FR to the original repo? :/

**Comment by gtsteffaniak** [comment]
> Are you about to implement this feature on your repo only or will make a FR to the original repo? :/

Typically no but it might be possible. The two repositories are quite different, but this might still be similar between the two I haven't looked.
